### ISSUE TITLE
Plugin Code Missing or Incomplete

### ISSUE THREAD

**Issue by zhbitzwz** [tarsal-oss/kflowd#1]
I have noticed that the plugin modules for kflowd, specifically the DNS, HTTP, Virus, Vulnerability, Device, Interface, and User-Group modules, appear to be empty or incomplete in the current repository. I am unable to find the implementation or any substantial code for these plugins in the provided directories.

**Comment by dirk29** [comment]
kflowd plugin modules are provided as open-binary shared objects (.so files) right now that can be loaded dynamically by kflowd at runtime. The plugin modules can be downloaded via this link: https://tarsal.co/kflowd-download-form
