### ISSUE TITLE
TCP + HTTPS (TLS)

### ISSUE THREAD

**Issue by mrbluecoat** [tarsal-oss/kflowd#2]
Cool project and thanks for sharing with the open source community! Does your `HTTP` plugin support TLS traffic (at least the SNI)? I see your example references `"Location ": " https://kflowd.github.io"` but it's not clear how you obtain that value.

**Comment by dirk29** [comment]
Thanks for your interest in kflowd. 

Right now kflowd only supports decoding of unencrypted http traffic via plugin module but we are currently working on a new plugin module that will also decode https and this module should become openly available in Q4.

The location header in the sample message you are referring to is the response to the original request that was still sent over http but indicating that the domain was permanently moved to an https location.
